polls/pollapp/urls.py
from django.urls import path
from django.http import HttpResponse
from . import views
from pollapp import views
from django.conf import settings
from django.conf.urls.static import static
from pollapp.views import UserindexView, AccountActivation, ProfileUpdate, PasswordChange, url_shortner, userLogin, Home

app_name = 'polls'
urlpatterns = [

    path('index/', views.IndexView.as_view(), name='index'),
    path('<int:question_id>/', views.DetailView.as_view(), name='detail'),
    path('<int:question_id>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.PollView.as_view(), name='vote'),
    path('register/', views.RegisterView.as_view(), name='register'),
    #path('sum', views.sum, name='sum'),

path('', views.Home,name='home'),
    #path('mysession', views.mysession, name='mysession'),
    path('userindexview/', UserindexView.as_view(), name='userindexview'),
    #path('userlogin/',views.LoginView.as_view(),name="userlogin"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('activate/<uidb64>/<token>',AccountActivation.as_view(), name='activate'),

    path('update/', views.ProfileUpdate.as_view(), name='update'),
    path('password/', views.PasswordChange.as_view(), name='password'),
    path('email', views.email,name='email'),
    #path('trial', views.trial.as_view(), name='trial'),
    #path('trial', views.trial, name='trial'),
    #path('email', views.email.as_view(), name='email'),


    path('paypal', views.Paypall.as_view(), name='paypal'),
    path('email_list_signup', views.email_list_signup, name='email_list_signup'),
    path('weather', views.Weather.as_view(), name='weather'),

    path('url-shortner',url_shortner.as_view(),name="url-shortner"),
    path('userlogin/', views.userLogin.as_view(), name="userlogin"),

    path('news', views.News_Application.as_view(),name="news"),


    path('barcode', views.Barcode.as_view(), name="barcode"),

    path('QRCodeGenerator', views.Qrcode.as_view(), name='QRCodeGenerator'),

    path('delete_view/<id>', views.Delete_View.as_view(), name='delete_view'),



path('screenshot', views.screenshot.as_view(),name='screenshot')]+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

polls/polls/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.contrib.auth.models import User
from django.urls import path, include, re_path
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView


from polls import views as polls_views

from django.contrib.auth import views as auth_views

from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
import debug_toolbar

urlpatterns = [

    path('admin/', admin.site.urls),

    path('accounts/', include('allauth.urls')),
    path('contact/', include('contactforms.urls')),
    #path('',TemplateView.as_view(template_name="userindexview.html")),

    path('__debug__/', include(debug_toolbar.urls)),
    path('users/', include('django.contrib.auth.urls')),
    path('captcha/', include('captcha.urls')),

    path('admin/defender/', include('defender.urls')), # defender admin

    path("password-reset", auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"),
         name="password_reset"),
    path("password-reset_done/",
         auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>",
         auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"),
         name="password_reset_confirm"),
    path("password-reset-complete/",
         auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name="password_reset_complete"),

]

urlpatterns += i18n_patterns (
    path('', include('pollapp.urls',namespace='pollapp'))
)
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings.LOGIN_URL = '/logout'

polls/pollapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Question(models.Model):
    objects = None
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


from django_countries.fields import CountryField
class Profile(models.Model):
    objects = None
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic = models.ImageField(blank=True,null=True,upload_to='images')
    phone = models.CharField(blank=True,null=True,max_length=10)
    country=CountryField()


    def get_image(self):
        try:
            url = self.profile_pic.url
        except:
            url = ''
        return url



class newsletter(models.Model):
    email = models.EmailField(max_length=100,unique=True)

    def __str__(self):
        return self.email
import barcode
from io import BytesIO
from barcode.writer import ImageWriter
from django.core.files import File
class Product(models.Model):
    name = models.CharField(max_length=100)
    barcode = models.ImageField(upload_to = 'barcode', blank=True)
    batch_number = models.CharField(max_length=12,null=True,unique=True)

    def save(self, *args, **kwargs):
        EAN = barcode.get_barcode_class('ean13')
        ean = EAN(f'{self.batch_number}', writer=ImageWriter())
        buffer = BytesIO()
        ean.write(buffer)
        self.barcode.save('barcode.png',File(buffer),save=False)
        return super().save(*args, **kwargs)



class QRCode(models.Model):
    url = models.URLField()
    image = models.ImageField(upload_to='qrcode',blank=True)

    def save(self,*args,**kwargs):

        super().save(*args,**kwargs)
    '''@property
    def qr(self):
        try:
            s = self.image.url
        except:
            s=""
        return s
    '''
class emp(models.Model):
    name = models.CharField(max_length=23)
    address = models.CharField(max_length=23)
    location = models.CharField(max_length=23)

polls/templates/polls/base.html
<!DOCTYPE html>

<html lang="en">

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Polls</title>
</head>

<body>
{% include 'results.html' %}
{% block body %}
{% endblock %}
 <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">Poll</a>
      &nbsp;
            &nbsp;
            &nbsp;
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 &nbsp;
            &nbsp;
            &nbsp;
  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
    &nbsp;
            &nbsp;
            &nbsp;
         &nbsp;
            &nbsp;
            &nbsp;
  <li class="nav-item active">
        <a class="nav-link" href="{% url 'polls:logout' %}">Logout <span class="sr-only">(current)</span></a>
      </li>
    </ul>

  <a class="navbar-brand"></a>

  </div>
</nav>
<br>
 <br>
 <br>




    <div class="container">
         <br>
        <div class="row">
            <div class=".col-md-6 m-auto">
{% block content %}


            </div>
        </div>
    </div>


<div class="footer">
  <p>Footer</p>
</div>

<style>
.footer {
   position: fixed;
   left: 0;
   bottom: 0;
   width: 100%;
   background-color: red;
   color: white;
   text-align: center;
}
</style>
  {% endblock %}
{% block js %}{% endblock %}
</body>

</html>

polls/templates/polls/detail.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'polls:index' %}">Back To Polls</a>
<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class="alert alert-danger">
    <strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post" id="form">
    {% csrf_token %}
    {{ form|crispy }}
    {% for choice in question.choice_set.all %}
    <div class="form-check">
        <input type="radio" name="choice" class="form-check-input" id="choice{{ forloop.counter }}"
            value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    </div>
    {% endfor %}
    <input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4" />
</form>



<script
        src="https://code.jquery.com/jquery-3.5.0.min.js"
        integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="
        crossorigin="anonymous"></script>

    <script>
    const form = document.getElementById('form');
    form.addEventListener("submit", submitHandler);

    function submitHandler(e) {
        e.preventDefault();
        $.ajax({
            type        : 'POST', // define the type of HTTP verb we want to use (POST for our form)
            url         : '{% url 'polls:vote' question.id %}', // the url where we want to POST
            data        : $('#form').serialize(), // our form data
            dataType    : 'json', // what type of data do we expect back from the server
            success     : successFunction
        });
    }

    function successFunction(msg) {
        console.log('hi')
        if (msg.message === 'Success') {
            if(!alert("sucess"))
            window.location.replace('{% url 'polls:results' question.id %}');
        }
        else{
        alert("error")

       }
    }
</script>

<br>

<br>

<br>

<br>

<br>

<br>

<br>


{% endblock %}

polls/templates/polls/footer.html
<!--<div class="footer">-->
<!--  <p>Footer</p>-->
<!--</div>-->

<!--<style>-->
<!--.footer {-->
<!--   position: fixed;-->
<!--   left: 0;-->
<!--   bottom: 0;-->
<!--   width: 100%;-->
<!--   background-color:  #007bff;-->
<!--   color: white;-->
<!--   text-align: center;-->
<!--}-->
<!--</style>-->
<style>
    .footer-basic {
  padding:40px 0;
  background-color: #007bff;
  color:#4b4c4d;
}

.footer-basic ul {
  padding:0;
  list-style:none;
  text-align:center;
  font-size:18px;
  line-height:1.6;
  margin-bottom:0;
}

.footer-basic li {
  padding:0 10px;
}

.footer-basic ul a {
  color:white;
  text-decoration:none;
  opacity:0.8;
}

.footer-basic ul a:hover {
  opacity:1;
}

.footer-basic .social {
  text-align:center;
  padding-bottom:25px;
}

.footer-basic .social > a {
  font-size:24px;
  width:40px;
  height:40px;
  line-height:40px;
  display:inline-block;
  text-align:center;
  border-radius:50%;
  border:1px solid #ccc;
  margin:0 8px;
  color:inherit;
  opacity:0.75;
}

.footer-basic .social > a:hover {
  opacity:0.9;
}

.footer-basic .copyright {
  margin-top:15px;
  text-align:center;
  font-size:13px;
  color:#aaa;
  margin-bottom:0;
}


</style>
<div class="footer-basic">
      <footer>

            <ul class="list-inline">
                <li class="list-inline-item"><a href="/">Polls</a></li>
                <li class="list-inline-item"><a href="/">Home</a></li>
                <li class="list-inline-item"><a href="{% url 'polls:register'%}">Register</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <p class="copyright">Blessy Cheriyan © 2021</p>
        </footer>
    </div>

polls/templates/polls/index.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center mb-3">Poll Questions</h1>
{% if latest_poll_list %}
{% for question in latest_poll_list %}
<div class="card-mb-3">
    <div class="card-body">
        <p class="lead">{{ question.question_text }}</p>
        <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary btn-sm">Vote Now</a>
        <a href="{% url 'polls:results' question.id %}" class="btn btn-secondary btn-sm">Results</a>
    </div>
</div>
{% endfor %}
{% else %}
<p>No polls available</p>
{% endif %}


{% endblock %}

polls/templates/polls/results.html
{% extends 'base.html' %}
{% block content %}
<h1 class="mb-5 text-center">{{ question.question_text }}</h1>

<ul class="list-group mb-5">
    {% for choice in question.choice_set.all %}
    <li class="list-group-item">
        {{ choice.choice_text }} <span class="badge badge-success float-right">{{ choice.votes }}
            vote{{ choice.votes | pluralize }}</span>
    </li>
    {% endfor %}
</ul>

<a class="btn btn-secondary" href="{% url 'polls:index' %}">Back To Polls</a>
<a class="btn btn-dark" href="{% url 'polls:detail' question.id %}">Vote again?</a>



<br>

<br>

<br>

<br>

{% endblock %}