polls/pollapp/urls.py
from django.urls import path
from django.http import HttpResponse
from . import views
from pollapp import views
from django.conf import settings
from django.conf.urls.static import static
from pollapp.views import UserindexView, AccountActivation, ProfileUpdate, PasswordChange, url_shortner, userLogin, Home

app_name = 'polls'
urlpatterns = [

    path('index/', views.IndexView.as_view(), name='index'),
    path('<int:question_id>/', views.DetailView.as_view(), name='detail'),
    path('<int:question_id>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.PollView.as_view(), name='vote'),
    path('register/', views.RegisterView.as_view(), name='register'),
    #path('sum', views.sum, name='sum'),

path('', views.Home,name='home'),
    #path('mysession', views.mysession, name='mysession'),
    path('userindexview/', UserindexView.as_view(), name='userindexview'),
    #path('userlogin/',views.LoginView.as_view(),name="userlogin"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('activate/<uidb64>/<token>',AccountActivation.as_view(), name='activate'),

    path('update/', views.ProfileUpdate.as_view(), name='update'),
    path('password/', views.PasswordChange.as_view(), name='password'),
    path('email', views.email,name='email'),
    #path('trial', views.trial.as_view(), name='trial'),
    #path('trial', views.trial, name='trial'),
    #path('email', views.email.as_view(), name='email'),


    path('paypal', views.Paypall.as_view(), name='paypal'),
    path('email_list_signup', views.email_list_signup, name='email_list_signup'),
    path('weather', views.Weather.as_view(), name='weather'),

    path('url-shortner',url_shortner.as_view(),name="url-shortner"),
    path('userlogin/', views.userLogin.as_view(), name="userlogin"),

    path('news', views.News_Application.as_view(),name="news"),


    path('barcode', views.Barcode.as_view(), name="barcode"),

    path('QRCodeGenerator', views.Qrcode.as_view(), name='QRCodeGenerator'),

    path('delete_view/<id>', views.Delete_View.as_view(), name='delete_view'),



path('screenshot', views.screenshot.as_view(),name='screenshot')]+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

polls/polls/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.contrib.auth.models import User
from django.urls import path, include, re_path
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView


from polls import views as polls_views

from django.contrib.auth import views as auth_views

from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
import debug_toolbar

urlpatterns = [

    path('admin/', admin.site.urls),

    path('accounts/', include('allauth.urls')),
    path('contact/', include('contactforms.urls')),
    #path('',TemplateView.as_view(template_name="userindexview.html")),

    path('__debug__/', include(debug_toolbar.urls)),
    path('users/', include('django.contrib.auth.urls')),
    path('captcha/', include('captcha.urls')),

    path('admin/defender/', include('defender.urls')), # defender admin

    path("password-reset", auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"),
         name="password_reset"),
    path("password-reset_done/",
         auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>",
         auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"),
         name="password_reset_confirm"),
    path("password-reset-complete/",
         auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name="password_reset_complete"),

]

urlpatterns += i18n_patterns (
    path('', include('pollapp.urls',namespace='pollapp'))
)
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings.LOGIN_URL = '/logout'

polls/templates/503.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<center>
  <h1> MAINTENANCE  MODE</h1>

</center>

</body>
</html>

polls/templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
           <p>
    You can login after: <b>{{cooloff_time_minutes|add:"0"}}minutes.</b></p>
<a href="http://127.0.0.1:8000/admin/"></a>
</body>
</html>

polls/templates/barcode.html
{% extends 'base.html' %}
{% block content %}

<body>


    {% if messages %}

    {% for message in messages %}

    <div class="alert alert-success text-center mt-5">{{message}}</div>
    {%endfor%}

    {%endif%}

    <div class="container text-center mt-5">

<h3 class="text-primary">Django Barcode</h3>
<hr>
<form method="post">{% csrf_token%}

<label for="Product">Product Name : - </label> <input required type="text" id="product" name="product-name"> <br><br>
<label for="Batch">Batch Number : - </label> <input required type="text" id="Batch" name="batch-number">
<br><br>

<button class="btn btn-primary">Generate Barcode</button>
</form>


    </div>


<div class="mt-5 container">

<div class="row">

    {% for product in p %}

    <div class="col-sm-4">
        <img src="{{product.barcode.url}}" class="img-fluid">
    </div>

    {%endfor%}
</div>

</div>

 {% endblock %}
</body>
</html>

polls/templates/base.html
<!doctype html>
<html lang="en">
  <head>


    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

  <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

      <style>
        .remove_button_css {
  outline: none;
  padding: 5px;
  border: 0px;
  box-sizing: none;
  background-color: transparent;
  color:white;
}
    </style>

  </head>
  <body>



<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="{% url 'polls:userindexview' %}">Polls</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'polls:userindexview' %}">Home <span class="sr-only">(current)</span></a>
      </li>
       <li class="nav-item active">
       <a class="nav-link" href="{% url 'polls:update' %}"><i class='far fa-edit' style='font-size:22px'>Edit</i> </a>
      </li>
         <li class="nav-item active">
       <a class="nav-link" href="{% url 'polls:paypal' %}">Paypal<span class="sr-only">(current)</span></a>
      </li>
           <li class="nav-item active">
        <a class="nav-link" href="{% url 'polls:password' %}">Change Password <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">

       <a class="nav-link" href="{% url 'polls:delete_view' request.user.pk  %}">Deactivate<span class="sr-only">(current)</span></a>
      </li>



      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Section
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'polls:weather' %}">Weather</a>
             <a class="dropdown-item" href="{% url 'polls:screenshot' %}">Screenshot</a>
          <a class="dropdown-item" href="{% url 'polls:url-shortner' %}">Url Shortener</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'polls:news' %}">News Applications</a>
             <a class="dropdown-item" href="{% url 'polls:barcode' %}">Create Barcode</a>
                <a class="dropdown-item" href="{% url 'polls:QRCodeGenerator' %}">Create Qrcodearcode</a>
        </div>
      </li>
  <li class="nav-item active">

      <form method="post" action="{% url 'account_logout' %}">
  {% csrf_token %}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
  {% endif %}
  <button type="submit" class="remove_button_css ">Logout</button>
</form>
<!--        <a class="nav-link" href="{% url 'polls:logout' %}">Logout <span class="sr-only">(current)</span></a>-->
      </li>


&nbsp;
&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;


       <li class="nav-item active pl-5">

        <h2 style="color:white";>{{user.first_name}} {{user.last_name}}    </h2>
      </li>
    </ul>

  </div>
</nav>







<br>
 <br>
 <br>




    <div class="container">
         <br>
        <div class="row">
            <div class=".col-md-6 m-auto">
{% block content %}
                  {% endblock %}


            </div>
        </div>
    </div>



{% include 'polls/footer.html'%}
</body>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

polls/templates/header.html
<!DOCTYPE html>

<html lang="en">

<head>


  <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body>


 <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" >Polls</a>
      &nbsp;
            &nbsp;
            &nbsp;
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 &nbsp;
            &nbsp;
            &nbsp;
  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>&nbsp;&nbsp;
    </ul>
  </div>
</nav>
<br>
 <br>
 <br>

    <div class="container">
         <br>
        <div class="row">
            <div class=".col-md-6 m-auto">
                {% block content %}

                  {% endblock %}


            </div>
        </div>
    </div>



{% include 'polls/footer.html'%}
</body>

</html>

polls/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <!-- css -->
    {%load static%}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Login</title>
  </head>
  <body>

   <!-- Message -->

   {% if messages%}

   {%for message in messages%}
<div class="container mt-3 message alert alert-{{message.tags}} text-center">{{message}}</div>
   {%endfor%}

   {%endif%}


   <!-- Regsitration form -->

   <div class="mt-5 login-form pb-3 shadow">
       <h3 class="p-3 text-center">Login Form</h3>
       <form method="POST" class="px-5 pt-4" novalidate> {% csrf_token%}


<label>Username</label><br>
<input type="text" name="username">
<br><br>

<label>password</label><br>
<input type="password" name="passw">

         <br><br>

<button class="btn" name="registration">Login</button>
       </form>
       <br>
       <small class="px-5 text-muted">need an account <a href="/registration/" style="text-decoration: none;">Signup</a></small>
   </div>
  </body>
</html>

polls/templates/news.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>News</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

<!-- css -->
<link rel="stylesheet" type="text/css" href="{% static 'CSS/style.css' %}">

  </head>
  <body>
     {% if page_obj.has_previous %}
    <!-- Nav part -->
<nav class="navbar shadow-lg fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/news/">
      <img src="{% static 'images/logo.png' %}" width="150px;">
    </a>
  </div>
</nav>

<div class="container text-center banner">

 <img src="{% static 'images/logo.png' %}" class="shadow-lg">
<hr style="color: white;">
</div>


 {% endif %}

{% for author,title,description,url,image,publishAt in news%}

<div class="container mt-5 news shadow-lg p-5">
  <div class="text-center">
  <img src="{{image}}" class="img-fluid">
</div>
<br>
<span class="text-white poppins-font"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
  <path fill-rule="ev
  enodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
</svg> By {{author}}</span> <span class="text-muted px-2"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar-date" viewBox="0 0 16 16">
  <path d="M6.445 11.688V6.354h-.633A12.6 12.6 0 0 0 4.5 7.16v.695c.375-.257.969-.62 1.258-.777h.012v4.61h.675zm1.188-1.305c.047.64.594 1.406 1.703 1.406 1.258 0 2-1.066 2-2.871 0-1.934-.781-2.668-1.953-2.668-.926 0-1.797.672-1.797 1.809 0 1.16.824 1.77 1.676 1.77.746 0 1.23-.376 1.383-.79h.027c-.004 1.316-.461 2.164-1.305 2.164-.664 0-1.008-.45-1.05-.82h-.684zm2.953-2.317c0 .696-.559 1.18-1.184 1.18-.601 0-1.144-.383-1.144-1.2 0-.823.582-1.21 1.168-1.21.633 0 1.16.398 1.16 1.23z"/>
  <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
</svg> {{publishAt}} </span> <hr style="color: white;">

<p class="poppins-font text-white">
  {{description}}
</p>
<br>
<a href="{{url}}" class="poppins-font shadow-lg p-2"> <b>Read more</b></a>


</div>


{%endfor%}





<!-- pagination -->

<div class="text-center container pagi shadow-lg p-3 my-5">

  {% if news.has_previous %}
<a class="poppins-font p-2" href="?page={{news.previous_page_number}}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
  <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
</svg> previous</a>
{%endif%}


<a class="p-2 active-btn poppins-font text-dark" style="background-color: #fff600;">{{news.number}}</a>


  {% if news.has_next %}

<a class="p-2 poppins-font" href="?page={{news.next_page_number}}">next <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
  <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
</svg></a>
{%endif%}

<!-- end pagination -->
</div>

<br><br>

<!-- top headlines -->

<div class="container headlines my-5">

<h1 class="poppins-font"><b>Top Headlines</b></h1><hr style="color: white;">

<div class="row">


{% for headline_author,headline_title,headline_description,headline_url,headline_image,headline_publishAt in headline %}

<div class="col-sm-4 shadow-lg p-5 border-top-0">
  <img src="{{headline_image}}" class="img-fluid">


<small class="text-white poppins-font"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
</svg> By  {{headline_author}}</small><br><br> <small class="text-muted px-2"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar-date" viewBox="0 0 16 16">
  <path d="M6.445 11.688V6.354h-.633A12.6 12.6 0 0 0 4.5 7.16v.695c.375-.257.969-.62 1.258-.777h.012v4.61h.675zm1.188-1.305c.047.64.594 1.406 1.703 1.406 1.258 0 2-1.066 2-2.871 0-1.934-.781-2.668-1.953-2.668-.926 0-1.797.672-1.797 1.809 0 1.16.824 1.77 1.676 1.77.746 0 1.23-.376 1.383-.79h.027c-.004 1.316-.461 2.164-1.305 2.164-.664 0-1.008-.45-1.05-.82h-.684zm2.953-2.317c0 .696-.559 1.18-1.184 1.18-.601 0-1.144-.383-1.144-1.2 0-.823.582-1.21 1.168-1.21.633 0 1.16.398 1.16 1.23z"/>
  <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
</svg> {{headline_publishAt}} </small> <hr style="color: white;">

<p class="poppins-font text-white">
  {{headline_description}}
</p>
<hr style="color: white;">
<a href="{{headline_url}}" class="poppins-font shadow-lg p-2"> <b>Read more</b></a>



</div>


  {%endfor%}


</div>




</div>





<!-- end top headlines -->




<!-- footer -->

<div class="container-fluid mt-5 footer shadow-lg text-center p-3">
  <span class="text-white poppins-font"><b>&copy;copyright 2021</b></span>
  <img class="mx-3" src="{% static 'images/logo.png' %}" width="100px;">
</div>

<!-- end footer -->
  </body>
</html>

polls/templates/newsletter.html
<!DOCTYPE html>
{% load crispy_forms_filters %}
<html lang="en">

<head>

<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v10.0&appId=861152141134748&autoLogAppEvents=1" nonce="VL9IxKG5"></script>
  <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


</head>

<body>

 <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">Polls</a>
      &nbsp;
            &nbsp;
            &nbsp;
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 &nbsp;
            &nbsp;
            &nbsp;
  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
    &nbsp;
            &nbsp;
            &nbsp;
         &nbsp;
            &nbsp;
            &nbsp;
  <li class="nav-item active">
        <a class="nav-link" href="{% url 'polls:userlogin' %}">Login <span class="sr-only">(current)</span></a>
      </li>

<form method="post" class="p-5" nonvalidate>{%csrf_token%}

     {{fm}} <button type="submit" class="btn btn-danger  btn-sm">Subcribe</button>
</form>


 <!-- Newsletter Section-->
    <section class="newsletter no-padding-top">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <h2>Subscribe to Newsletter</h2>
            <p class="text-big">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          </div>
          <div class="col-md-8">
            <div class="form-holder">
              <form  method="POST">
                {% csrf_token %}
                <div class="form-group">
                    {{ fm }}
                    <button type="submit" class="submit">Signup</button>
                </div>a
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
</body>
</html>

polls/templates/qrcode.html
{% extends 'base.html' %}
{% load static %}
{% load qr_code %}

{% block content %}
<center>
<div class="container qrcode">
<form method="post" class="text-center mt-5 d-flex"  enctype="multipart/form-data">
    {% csrf_token %}
  <input type="url" placeholder="type an url" required name="url" class="form-control" >

     <button class="btn btn-primary mx-3">Generate Qrcode</button>
</form>
</div>

  <div class="container text-center mt-5">

<div class="row">

    {% for qr in qr_code %}

<div class="col-sm-4 border p-3">
<!--    <img src={{qr.qr}}><br>-->
    {% qr_from_text qr.url size="s" image_format="png" error_correction="L" %}
    <small>

        {{qr.url}}</small>

    </div>

  {%endfor%}
</div>
  </div>
</center>
{%endblock%}